name: ci it.bz.noi.community-api

on:
  push:
    branches: [ main, development ]
    paths:
      - "!README.md"
  pull_request:
    branches: [ main, development ]
    paths:
      - "!README.md"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE: noiapp
      DOCKER_TAG: latest
      SERVER_PORT: "1244" 

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure
        run: |
          rm -f .env
          echo 'DOCKER_IMAGE=${DOCKER_IMAGE}' >> .env
          echo 'DOCKER_TAG=${DOCKER_TAG}' >> .env
          echo 'SERVER_PORT=${SERVER_PORT}' >> .env

      - name: Build
        run: docker-compose -f docker-compose.yml build
    
      - name: Shut down
        run: docker-compose -f docker-compose.yml down || true
